project_id = "zldnuanexjfhdnpdxdyy"

[functions.fetch-nibo-boletos]
verify_jwt = false

[functions.sync-nibo-status]
verify_jwt = false

[functions.delete-all-boletos]
verify_jwt = false

[functions.check-monthly-boletos]
verify_jwt = false
